spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSl=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456qq
  devtools:
    restart:
      enabled: true
  config:
    activate:
      on-profile: dev
### redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
### mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
### jwt配置
jwt:
  issuer: zyr
  secret: zyr030426
  expiration: 30
---
server:
  port: 81
spring:
  config:
    activate:
      on-profile: active