spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSl=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456qq
  devtools:
    restart:
      enabled: true
  config:
    activate:
      on-profile: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
server:
  port: 81
spring:
  config:
    activate:
      on-profile: active